select
    sale_id,
    sale_date as date,
    customer_id,
    product_id,
    store_id,
    quantity,
    total_amount,
    customer_first_name as first_name,
    customer_last_name as last_name,
    customer_email as email,
    customer_phone_number as phone_number,
    customer_date_of_birth as dob,
    customer_gender as gender,
    customer_registration_date as registration_date,
    customer_street_address as address,
    customer_city as city,
    customer_state as state,
    customer_postal_code as postal_code,
    product_name,
    product_category,
    product_brand,
    product_price,
    product_description,
    product_stock_quantity,
    product_date_added,
    store_name,
    store_location,
    store_manager,
    store_opening_date,
    return_id,
    return_date,
    return_quantity,
    return_total_amount,
    date_id,
    day,
    week,
    month,
    quarter,
    year
from
    {{source('sales_data','rawsales')}}